### ISSUE TITLE
FarmProxy Shows Workers as Connected but not individual hashrates

### ISSUE THREAD

**Issue by praeluceo** [braiins/farm-proxy#14]
This may be considered a feature request, but when configured with individual workers, FarmProxy fails to show the individual worker performance: accepted shares, rejected shares, average hashrate, etc.

A view of a stacked graph and statistics similar to what would be seen on the pool manager side (such as on the Braiins worker dashboard) would be ideal, so local statistics could be viewed per worker, without needing to go to the web.

**Comment by Canefis** [comment]
> This may be considered a feature request, but when configured with individual workers, FarmProxy fails to show the individual worker performance: accepted shares, rejected shares, average hashrate, etc.
> 
> A view of a stacked graph and statistics similar to what would be seen on the pool manager side (such as on the Braiins worker dashboard) would be ideal, so local statistics could be viewed per worker, without needing to go to the web.

Yes, agree, it is good idea. Can we modify json code for the dashboard panel for our own?

**Comment by jprchal-braiins** [comment]
Hi, we don't plan such a feature. Actually we are going to remove the miner IP address from the metrics of downstream hashrate, because for bigger farms it slows down whole reporting substantially. You can run [Farm Monitor](https://academy.braiins.com/en/farm-monitor/about/) to view hashrate per worker.
