### ISSUE TITLE
Hashrate split

### ISSUE THREAD

**Issue by yagema404** [braiins/farm-proxy#8]
How does hashrate splitting work? I've set everything up, but the hashrate goes to only one pool

<img width="415" alt="Screenshot 2022-05-23 at 11 26 37" src="https://user-images.githubusercontent.com/33048363/169776922-046fbede-4d76-4905-a9bf-2af79d0c6e4e.png">
<img width="1255" alt="Screenshot 2022-05-23 at 11 26 54" src="https://user-images.githubusercontent.com/33048363/169776983-465dd64e-8e3d-4eae-8ff5-9af19fad461d.png">

**Comment by yagema404** [comment]
I want to split one ASIC with a hashrate of 50th/s into two

**Comment by papampi** [comment]
Welcome to the club ... 
Not possible, it splits miners not hash rate

Best you can do is setup multi pool group and quota in miner settings

**Comment by yagema404** [comment]
It is sad :(
I would like this feature

**Comment by papampi** [comment]
From my tests, if you have 2 miners with different hash rates (i.e: 20 and 40 Th/s) and split by 50:50 weights
It splits them randomly.
So one account will get 20 Th/s and other will get 40

**Comment by papampi** [comment]
Also remember weight is not percent, if you set 50:50 it tries to set 50 miners to one goal and 50 miners to another
Try to set weights base on your miner counts.
So if you have 2 miners and set 50:50 , it tries to set 50 miners to one goal and 50 to other, So all hashrate will go to one goal.
But if you set the goal to 1:1 it send one miner to one goal and one to another

**Comment by yagema404** [comment]
@papampi got it, thanks you

**Comment by papampi** [comment]
These are from my tests, and may not be 100% correct.

**Comment by vitficl** [comment]
Hi @yagema404,

I am Vit from Braiins. I confirm that the hashrate could be split on the miner(s) level, it means that you can't go level down to split hashrate of the 1 miner. This can be done in Braiins OS+ using Pool Groups in the configuration of the miner.

Ragarding to the hashrate weights: Attribute **hr_weight** stands for hashrate distribution ratio preference. Beware of the weight and not the percentage. For example, the ratio of weights 2:1 will distribute the hashrate into target endpoints approx. 67% of hashrate goes into target with weight 2 and 33% of hashrate goes into target with weight 1. But keep in mind this works well if you mine with several devices, because it finest granularity for splitting is device itself as mentioned above. It is explained in the documentation, check it out [here](https://docs.braiins.com/farm-proxy-en/User%20Guide/index_guide.html).

**Comment by Canefis** [comment]
I connected 9 miners, but anyway cannot split a hashrate, what am I doing wrong?

**Comment by 0xStratix** [comment]
Hi, you can use our solution for you problem

**Comment by Canefis** [comment]
Thanks. But I built own proxy with difficulty multiplexer and hashrate balancing (ewma +PI controller). Working ultra fast and perfect on rust
